### ISSUE TITLE
Renaming a file removes it from IWAD and Source Port Additional Files

### ISSUE THREAD

**Issue by robbinsrush** [hobomaster22/DoomLauncher#49]
Before:

![image](https://user-images.githubusercontent.com/25468624/45471917-6a2f8580-b6e7-11e8-8450-6c979b538be4.png)

Renaming:

![image](https://user-images.githubusercontent.com/25468624/45471924-70256680-b6e7-11e8-9f07-e4ad488a3fff.png)

After:

![image](https://user-images.githubusercontent.com/25468624/45471926-74518400-b6e7-11e8-8758-47bcac5a2132.png)

**Comment by guynamederick** [comment]
This also occurs with IWAD files, so editing title. Thanks for reporting.

**Comment by hobomaster22** [comment]
This is because the additional files are referenced by their filename string. Once the file is renamed it can no longer be found and nothing will be displayed. This is a significant change because the additional files would have to reference them by their database ID instead. Will likely push this fix off for 2.6.4.0

**Comment by hobomaster22** [comment]
Fixed on development.
