### ISSUE TITLE
[Feature Request] Handling of game files

### ISSUE THREAD

**Issue by PopeRigby** [hobomaster22/DoomLauncher#87]
1. Have the location of game files be all configurable
2. Don't require a mod's folder to be an archive (is this possible?)
3. Don't automatically archive IWADs

I think this would make file management a lot easier. As it stands right now, all files you add to your library are copied over to the DoomLauncher folder and archived. This makes organizing everything very difficult because you can't have your mods separated into categories, for example `PWADs/Gameplay/BrutalDoom` or `IWADs/DOOM2.WAD,` and you also end up with all the mod files being archived, which also can be annoying.

**Comment by guynamederick** [comment]
If I can recall, the GameWads folder in the past had the IWADs unarchived there before everything just went into the GameFiles directory, and so far it has been favorable in my experience. I'm don't think going for more configurations would be necessary since tags can be useful like having organized folders and you can right click on a game file and open a new tab to see what is inside the .zip archive.

I'm curious, what issues are there for mods to not be in a .zip archive? As far as I am aware, .pk3 ZDoom mods are already compressed (therefore an archive) so there won't be a major difference in gaining/saving data. As for WAD files, since they are uncompressed saving so them into a .zip archive has helped in reducing the overall size of a Doom game directory.

Honestly, what you're requesting can be handled by other launchers (that are merely just frontends) since you can manage directories better that way. Doom Launcher is helpful in being both a frontend and like a database, if that makes sense.

**Comment by PopeRigby** [comment]
That does make sense. I'll try using it like that.

**Comment by hobomaster22** [comment]
Doom Launcher is intended to be a frontend that handles all file management. There really isn't a reason to go digging in folders. You can access anything from the launcher including opening the file by right clicking. You can add additional tabs by creating tags and tagging files to categorize them however you want. I highly recommend viewing the Help pdf to see everything it can do. You can access Help through the main menu.

**Comment by guynamederick** [comment]
One feature you should read into from the Help file is selecting a file to automatically launch with a source port or IWAD. No need for another directory or anything since that will launch what you want to use alongside whatever mapset you're going to play. With tags, additional file loading, and even a search bar to find what you're looking for, there is no need to have this kind of configuring you're thinking of as mentioned above.
